#ifndef __PROJ_CFG_VLLINK_LITE_H__
#define __PROJ_CFG_VLLINK_LITE_H__

#define PROJ_CFG_GD32F3X0_HSI48M_USB_PLL_128M_OVERCLOCK
//#define PROJ_CFG_GD32F3X0_HSI48M_USB_PLL_108M
#define PROJ_CFG_CORE_INIT_TINY
#define VSF_SYSTIMER_FREQ                   (CHIP_AHB_FREQ_HZ)

#endif // __PROJ_CFG_VLLINK_LITE_H__
