#ifndef __TOP_APP_CFG_H__
#define __TOP_APP_CFG_H__

#include "compile_definitions.h"
#include "proj_cfg.h"
#include "brd_cfg.h"

//#define ASSERT(...)                     			if (!(__VA_ARGS__)) {while(1);};
#define ASSERT(...)

//#define VSF_OS_CFG_EVTQ_POOL_SIZE					16
#define VSF_OS_CFG_EVTQ_BITSIZE						3
#define VSF_OS_CFG_PRIORITY_NUM						1
#define VSF_KERNEL_CFG_SUPPORT_SYNC					ENABLED
#define VSF_KERNEL_CFG_SUPPORT_PREMPT				DISABLED
#define VSF_KERNEL_CFG_SUPPORT_DYNAMIC_PRIOTIRY		DISABLED

#define VSF_KERNEL_CFG_EDA_SUPPORT_PT				DISABLED
#define VSF_KERNEL_CFG_EDA_SUPPORT_TIMER			DISABLED
#define VSF_KERNEL_CFG_EDA_SUPPORT_FSM				DISABLED
#define VSF_KERNEL_CFG_EDA_SUPPORT_SUB_CALL			DISABLED

#define VSF_KERNEL_CFG_SUPPORT_MSG_QUEUE			DISABLED
#define VSF_KERNEL_CFG_CALLBACK_TIMER				DISABLED
#define VSF_KERNEL_CFG_SUPPORT_BITMAP_EVENT			DISABLED

#define VSF_KERNEL_CFG_TRACE						DISABLED
//#define VSF_OS_CFG_MAIN_STACK_SIZE				2048

#define VSF_OS_CFG_MAIN_MODE						VSF_OS_CFG_MAIN_MODE_IDLE

#define VSF_USE_KERNEL_SIMPLE_SHELL					DISABLED
#define VSF_KERNEL_CFG_SUPPORT_THREAD				DISABLED

#define VSF_USE_HEAP								DISABLED
#	define VSF_HEAP_CFG_MCB_MAGIC_EN				DISABLED

#define VSF_USE_USB_DEVICE							ENABLED
#   define VSF_USBD_CFG_USE_EDA						ENABLED
#   define VSF_USE_USB_DEVICE_DCD_DWCOTG			ENABLED
#   define VSF_USBD_CFG_SPEED						USB_SPEED_FULL
#   define APP_CFG_USBD_VID                         0x1209
#   define APP_CFG_USBD_PID                         0x6666
#   define APP_CFG_USBD_BCD                         0x0001

#endif

