#ifndef __PROJ_CFG_H__
#define __PROJ_CFG_H__

#if defined(BOARD_TYPE_VLLINK_LITE)
#	include "proj_cfg_vllink_lite.h"
#endif

#ifdef PROJC_CFG_CMSIS_DAP_V1_SUPPORT
#	define CMSIS_DAP_V1_DESC_LENGTH			32
#	define CMSIS_DAP_V1_INTERFACE_COUNT		1
#else
#	define CMSIS_DAP_V1_DESC_LENGTH			0
#	define CMSIS_DAP_V1_INTERFACE_COUNT		0
#endif
#ifdef PROJC_CFG_CMSIS_DAP_V2_SUPPORT
#	define CMSIS_DAP_V2_DESC_LENGTH			23
#	define CMSIS_DAP_V2_INTERFACE_COUNT		1
#else
#	define CMSIS_DAP_V2_DESC_LENGTH			0
#	define CMSIS_DAP_V2_INTERFACE_COUNT		0
#endif
#ifdef PROJC_CFG_CDCEXT_SUPPORT
#	define CDCEXT_DESC_LENGTH				66
#	define CDCEXT_INTERFACE_COUNT			2
#else
#	define CDCEXT_DESC_LENGTH				0
#	define CDCEXT_INTERFACE_COUNT			0
#endif
#ifdef PROJC_CFG_CDCSHELL_SUPPORT
#	define CDCSHELL_DESC_LENGTH				66
#	define CDCSHELL_INTERFACE_COUNT			2
#else
#	define CDCSHELL_DESC_LENGTH				0
#	define CDCSHELL_INTERFACE_COUNT			0
#endif

#define USBD_CONFIGDESC_LENGTH		(9 + CMSIS_DAP_V1_DESC_LENGTH + CMSIS_DAP_V2_DESC_LENGTH + CDCEXT_DESC_LENGTH + CDCSHELL_DESC_LENGTH)
#define USBD_INTERFACE_COUNT		(CMSIS_DAP_V1_INTERFACE_COUNT + CMSIS_DAP_V2_INTERFACE_COUNT + CDCEXT_INTERFACE_COUNT + CDCSHELL_INTERFACE_COUNT)


#endif // __PROJ_CFG_H__

